// Copyright 2022 - 2023 GZSkins, Inc. All rights reserved.
// Licensed under the Mozilla Public License, Version 2.0 (the "License.txt").
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

namespace GZSkinsX.Uwp.IO.Extensions;

/// <summary>
/// 
/// </summary>
public static class WindowCorePropertiesConverter
{
    /// <summary>
    /// 
    /// </summary>
    /// <param name="value"></param>
    /// <returns></returns>
    /// <exception cref="System.InvalidOperationException"></exception>
    public static string Convert(WindowCoreProperties value) => value switch
    {
        WindowCoreProperties.System_AcquisitionID => "System.AcquisitionID",
        WindowCoreProperties.System_ApplicationDefinedProperties => "System.ApplicationDefinedProperties",
        WindowCoreProperties.System_ApplicationName => "System.ApplicationName",
        WindowCoreProperties.System_AppZoneIdentifier => "System.AppZoneIdentifier",
        WindowCoreProperties.System_Author => "System.Author",
        WindowCoreProperties.System_CachedFileUpdaterContentIdForConflictResolution => "System.CachedFileUpdaterContentIdForConflictResolution",
        WindowCoreProperties.System_CachedFileUpdaterContentIdForStream => "System.CachedFileUpdaterContentIdForStream",
        WindowCoreProperties.System_Capacity => "System.Capacity",
        WindowCoreProperties.System_Category => "System.Category",
        WindowCoreProperties.System_Comment => "System.Comment",
        WindowCoreProperties.System_Company => "System.Company",
        WindowCoreProperties.System_ComputerName => "System.ComputerName",
        WindowCoreProperties.System_ContainedItems => "System.ContainedItems",
        WindowCoreProperties.System_ContentStatus => "System.ContentStatus",
        WindowCoreProperties.System_ContentType => "System.ContentType",
        WindowCoreProperties.System_Copyright => "System.Copyright",
        WindowCoreProperties.System_CreatorAppId => "System.CreatorAppId",
        WindowCoreProperties.System_CreatorOpenWithUIOptions => "System.CreatorOpenWithUIOptions",
        WindowCoreProperties.System_DataObjectFormat => "System.DataObjectFormat",
        WindowCoreProperties.System_DateAccessed => "System.DateAccessed",
        WindowCoreProperties.System_DateAcquired => "System.DateAcquired",
        WindowCoreProperties.System_DateArchived => "System.DateArchived",
        WindowCoreProperties.System_DateCompleted => "System.DateCompleted",
        WindowCoreProperties.System_DateCreated => "System.DateCreated",
        WindowCoreProperties.System_DateImported => "System.DateImported",
        WindowCoreProperties.System_DateModified => "System.DateModified",
        WindowCoreProperties.System_DefaultSaveLocationDisplay => "System.DefaultSaveLocationDisplay",
        WindowCoreProperties.System_DueDate => "System.DueDate",
        WindowCoreProperties.System_EndDate => "System.EndDate",
        WindowCoreProperties.System_ExpandoProperties => "System.ExpandoProperties",
        WindowCoreProperties.System_FileAllocationSize => "System.FileAllocationSize",
        WindowCoreProperties.System_FileAttributes => "System.FileAttributes",
        WindowCoreProperties.System_FileCount => "System.FileCount",
        WindowCoreProperties.System_FileDescription => "System.FileDescription",
        WindowCoreProperties.System_FileExtension => "System.FileExtension",
        WindowCoreProperties.System_FileFRN => "System.FileFRN",
        WindowCoreProperties.System_FileName => "System.FileName",
        WindowCoreProperties.System_FileOfflineAvailabilityStatus => "System.FileOfflineAvailabilityStatus",
        WindowCoreProperties.System_FileOwner => "System.FileOwner",
        WindowCoreProperties.System_FilePlaceholderStatus => "System.FilePlaceholderStatus",
        WindowCoreProperties.System_FileVersion => "System.FileVersion",
        WindowCoreProperties.System_FindData => "System.FindData",
        WindowCoreProperties.System_FlagColor => "System.FlagColor",
        WindowCoreProperties.System_FlagColorText => "System.FlagColorText",
        WindowCoreProperties.System_FlagStatus => "System.FlagStatus",
        WindowCoreProperties.System_FlagStatusText => "System.FlagStatusText",
        WindowCoreProperties.System_FolderKind => "System.FolderKind",
        WindowCoreProperties.System_FolderNameDisplay => "System.FolderNameDisplay",
        WindowCoreProperties.System_FreeSpace => "System.FreeSpace",
        WindowCoreProperties.System_FullText => "System.FullText",
        WindowCoreProperties.System_HighKeywords => "System.HighKeywords",
        WindowCoreProperties.System_ImageParsingName => "System.ImageParsingName",
        WindowCoreProperties.System_Importance => "System.Importance",
        WindowCoreProperties.System_ImportanceText => "System.ImportanceText",
        WindowCoreProperties.System_IsAttachment => "System.IsAttachment",
        WindowCoreProperties.System_IsDefaultNonOwnerSaveLocation => "System.IsDefaultNonOwnerSaveLocation",
        WindowCoreProperties.System_IsDefaultSaveLocation => "System.IsDefaultSaveLocation",
        WindowCoreProperties.System_IsDeleted => "System.IsDeleted",
        WindowCoreProperties.System_IsEncrypted => "System.IsEncrypted",
        WindowCoreProperties.System_IsFlagged => "System.IsFlagged",
        WindowCoreProperties.System_IsFlaggedComplete => "System.IsFlaggedComplete",
        WindowCoreProperties.System_IsIncomplete => "System.IsIncomplete",
        WindowCoreProperties.System_IsLocationSupported => "System.IsLocationSupported",
        WindowCoreProperties.System_IsPinnedToNameSpaceTree => "System.IsPinnedToNameSpaceTree",
        WindowCoreProperties.System_IsRead => "System.IsRead",
        WindowCoreProperties.System_IsSearchOnlyItem => "System.IsSearchOnlyItem",
        WindowCoreProperties.System_IsSendToTarget => "System.IsSendToTarget",
        WindowCoreProperties.System_IsShared => "System.IsShared",
        WindowCoreProperties.System_ItemAuthors => "System.ItemAuthors",
        WindowCoreProperties.System_ItemClassType => "System.ItemClassType",
        WindowCoreProperties.System_ItemDate => "System.ItemDate",
        WindowCoreProperties.System_ItemFolderNameDisplay => "System.ItemFolderNameDisplay",
        WindowCoreProperties.System_ItemFolderPathDisplay => "System.ItemFolderPathDisplay",
        WindowCoreProperties.System_ItemFolderPathDisplayNarrow => "System.ItemFolderPathDisplayNarrow",
        WindowCoreProperties.System_ItemName => "System.ItemName",
        WindowCoreProperties.System_ItemNameDisplay => "System.ItemNameDisplay",
        WindowCoreProperties.System_ItemNameDisplayWithoutExtension => "System.ItemNameDisplayWithoutExtension",
        WindowCoreProperties.System_ItemNamePrefix => "System.ItemNamePrefix",
        WindowCoreProperties.System_ItemNameSortOverride => "System.ItemNameSortOverride",
        WindowCoreProperties.System_ItemParticipants => "System.ItemParticipants",
        WindowCoreProperties.System_ItemPathDisplay => "System.ItemPathDisplay",
        WindowCoreProperties.System_ItemPathDisplayNarrow => "System.ItemPathDisplayNarrow",
        WindowCoreProperties.System_ItemSubType => "System.ItemSubType",
        WindowCoreProperties.System_ItemType => "System.ItemType",
        WindowCoreProperties.System_ItemTypeText => "System.ItemTypeText",
        WindowCoreProperties.System_ItemUrl => "System.ItemUrl",
        WindowCoreProperties.System_Keywords => "System.Keywords",
        WindowCoreProperties.System_Kind => "System.Kind",
        WindowCoreProperties.System_KindText => "System.KindText",
        WindowCoreProperties.System_Language => "System.Language",
        WindowCoreProperties.System_LastSyncError => "System.LastSyncError",
        WindowCoreProperties.System_LastWriterPackageFamilyName => "System.LastWriterPackageFamilyName",
        WindowCoreProperties.System_LowKeywords => "System.LowKeywords",
        WindowCoreProperties.System_MediumKeywords => "System.MediumKeywords",
        WindowCoreProperties.System_MileageInformation => "System.MileageInformation",
        WindowCoreProperties.System_MIMEType => "System.MIMEType",
        WindowCoreProperties.System_Null => "System.Null",
        WindowCoreProperties.System_OfflineAvailability => "System.OfflineAvailability",
        WindowCoreProperties.System_OfflineStatus => "System.OfflineStatus",
        WindowCoreProperties.System_OriginalFileName => "System.OriginalFileName",
        WindowCoreProperties.System_OwnerSID => "System.OwnerSID",
        WindowCoreProperties.System_ParentalRating => "System.ParentalRating",
        WindowCoreProperties.System_ParentalRatingReason => "System.ParentalRatingReason",
        WindowCoreProperties.System_ParentalRatingsOrganization => "System.ParentalRatingsOrganization",
        WindowCoreProperties.System_ParsingBindContext => "System.ParsingBindContext",
        WindowCoreProperties.System_ParsingName => "System.ParsingName",
        WindowCoreProperties.System_ParsingPath => "System.ParsingPath",
        WindowCoreProperties.System_PerceivedType => "System.PerceivedType",
        WindowCoreProperties.System_PercentFull => "System.PercentFull",
        WindowCoreProperties.System_Priority => "System.Priority",
        WindowCoreProperties.System_PriorityText => "System.PriorityText",
        WindowCoreProperties.System_Project => "System.Project",
        WindowCoreProperties.System_ProviderItemID => "System.ProviderItemID",
        WindowCoreProperties.System_Rating => "System.Rating",
        WindowCoreProperties.System_RatingText => "System.RatingText",
        WindowCoreProperties.System_RemoteConflictingFile => "System.RemoteConflictingFile",
        WindowCoreProperties.System_Sensitivity => "System.Sensitivity",
        WindowCoreProperties.System_SensitivityText => "System.SensitivityText",
        WindowCoreProperties.System_SFGAOFlags => "System.SFGAOFlags",
        WindowCoreProperties.System_SharedWith => "System.SharedWith",
        WindowCoreProperties.System_ShareUserRating => "System.ShareUserRating",
        WindowCoreProperties.System_SharingStatus => "System.SharingStatus",
        WindowCoreProperties.System_Shell_OmitFromView => "System.Shell.OmitFromView",
        WindowCoreProperties.System_SimpleRating => "System.SimpleRating",
        WindowCoreProperties.System_Size => "System.Size",
        WindowCoreProperties.System_SoftwareUsed => "System.SoftwareUsed",
        WindowCoreProperties.System_SourceItem => "System.SourceItem",
        WindowCoreProperties.System_SourcePackageFamilyName => "System.SourcePackageFamilyName",
        WindowCoreProperties.System_StartDate => "System.StartDate",
        WindowCoreProperties.System_Status => "System.Status",
        WindowCoreProperties.System_StorageProviderCallerVersionInformation => "System.StorageProviderCallerVersionInformation",
        WindowCoreProperties.System_StorageProviderError => "System.StorageProviderError",
        WindowCoreProperties.System_StorageProviderFileChecksum => "System.StorageProviderFileChecksum",
        WindowCoreProperties.System_StorageProviderFileIdentifier => "System.StorageProviderFileIdentifier",
        WindowCoreProperties.System_StorageProviderFileRemoteUri => "System.StorageProviderFileRemoteUri",
        WindowCoreProperties.System_StorageProviderFileVersion => "System.StorageProviderFileVersion",
        WindowCoreProperties.System_StorageProviderFileVersionWaterline => "System.StorageProviderFileVersionWaterline",
        WindowCoreProperties.System_StorageProviderId => "System.StorageProviderId",
        WindowCoreProperties.System_StorageProviderShareStatuses => "System.StorageProviderShareStatuses",
        WindowCoreProperties.System_StorageProviderSharingStatus => "System.StorageProviderSharingStatus",
        WindowCoreProperties.System_StorageProviderStatus => "System.StorageProviderStatus",
        WindowCoreProperties.System_Subject => "System.Subject",
        WindowCoreProperties.System_SyncTransferStatus => "System.SyncTransferStatus",
        WindowCoreProperties.System_Thumbnail => "System.Thumbnail",
        WindowCoreProperties.System_ThumbnailCacheId => "System.ThumbnailCacheId",
        WindowCoreProperties.System_ThumbnailStream => "System.ThumbnailStream",
        WindowCoreProperties.System_Title => "System.Title",
        WindowCoreProperties.System_TitleSortOverride => "System.TitleSortOverride",
        WindowCoreProperties.System_TotalFileSize => "System.TotalFileSize",
        WindowCoreProperties.System_Trademarks => "System.Trademarks",
        WindowCoreProperties.System_TransferOrder => "System.TransferOrder",
        WindowCoreProperties.System_TransferPosition => "System.TransferPosition",
        WindowCoreProperties.System_TransferSize => "System.TransferSize",
        WindowCoreProperties.System_VolumeId => "System.VolumeId",
        WindowCoreProperties.System_ZoneIdentifier => "System.ZoneIdentifier",
        _ => throw new System.InvalidOperationException($"Invalid WindowCoreProeprties: {value}"),
    };
}
