//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GZSkinsX.DesktopExtension.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GZSkinsX.DesktopExtension.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缺少必要的模块，该操作无法进行。.
        /// </summary>
        internal static string Interop_Exception_ModuleNotFound {
            get {
                return ResourceManager.GetString("Interop_Exception_ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在读取文件内容时出现了未知的错误，&quot;{0}&quot;。.
        /// </summary>
        internal static string Kernel_Exception_CannotToReadContent {
            get {
                return ResourceManager.GetString("Kernel_Exception_CannotToReadContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的文件头标识，&quot;{0}&quot;。.
        /// </summary>
        internal static string Kernel_Exception_InvalidFileHeader {
            get {
                return ResourceManager.GetString("Kernel_Exception_InvalidFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未在模组文件中找到有效的模组信息，&quot;{0}&quot;。.
        /// </summary>
        internal static string Kernel_Exception_ItemNotFound {
            get {
                return ResourceManager.GetString("Kernel_Exception_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在读取文件时发生了意料之外的错误，&quot;{0}&quot;。.
        /// </summary>
        internal static string Kernel_Exception_Unknown {
            get {
                return ResourceManager.GetString("Kernel_Exception_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持的文件版本，&quot;{0}&quot;。.
        /// </summary>
        internal static string Kernel_Exception_UnsupportedFileVersion {
            get {
                return ResourceManager.GetString("Kernel_Exception_UnsupportedFileVersion", resourceCulture);
            }
        }
    }
}
