// <auto-generated by App.g.tt (t4 template file). />
 
// Copyright 2022 - 2023 GZSkins, Inc. All rights reserved.
// Licensed under the Mozilla Public License, Version 2.0 (the "License.txt").
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

namespace GZSkinsX;

public sealed partial class App
{
    /// <summary>
    /// 获取当前 Appx 引用程序集
    /// </summary>
    private static global::System.Collections.Generic.IEnumerable<global::System.Reflection.Assembly> GetAssemblies()
    {
        // Main Appx
        {
            // Self Assembly
            yield return typeof(global::GZSkinsX.App).Assembly;
            // GZSkinsX.Api
            yield return typeof(global::GZSkinsX.Api.Appx.IAppxWindow).Assembly;
            // GZSkinsX.Appx.AccessCache
            yield return typeof(global::GZSkinsX.Appx.AccessCache.AppxAccessCache).Assembly;
            // GZSkinsX.Appx.Game
            yield return typeof(global::GZSkinsX.Appx.Game.AppxGame).Assembly;
            // GZSkinsX.Appx.Mods
            yield return typeof(global::GZSkinsX.Appx.Mods.AppxMods).Assembly;
            // GZSkinsX.Appx.MRT
            yield return typeof(global::GZSkinsX.Appx.MRT.AppxMRT).Assembly;
            // GZSkinsX.Appx.Navigation
            yield return typeof(global::GZSkinsX.Appx.Navigation.AppxNavigation).Assembly;
            // GZSkinsX.Appx.Preload
            yield return typeof(global::GZSkinsX.Appx.Preload.AppxPreload).Assembly;
            // GZSkinsX.Appx.Settings
            yield return typeof(global::GZSkinsX.Appx.Settings.AppxSettings).Assembly;
            // GZSkinsX.Appx.StartUp
            yield return typeof(global::GZSkinsX.Appx.StartUp.AppxStartUp).Assembly;
            // GZSkinsX.Appx.WindowManager
            yield return typeof(global::GZSkinsX.Appx.WindowManager.AppxWindowManager).Assembly;
        }
    }
}
