// <auto-generated by AppxContext.Services.g.tt (t4 template file). />

// Copyright 2022 - 2023 GZSkins, Inc. All rights reserved.
// Licensed under the Mozilla Public License, Version 2.0 (the "License.txt").
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#nullable enable

namespace GZSkinsX.SDK.Appx;

public static partial class AppxContext
{
    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.AccessCache.IFutureAccessService"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.AccessCache.IFutureAccessService FutureAccessService
    {
        get => CheckAccess(ref s_futureAccessService);
    }

    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.AccessCache.IMostRecentlyUsedService"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.AccessCache.IMostRecentlyUsedService MostRecentlyUsedItemService
    {
        get => CheckAccess(ref s_mostRecentlyUsedItemService);
    }

    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.Appx.IAppxWindow"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.Appx.IAppxWindow AppxWindow
    {
        get => CheckAccess(ref s_appxWindow);
    }

    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.Appx.IAppxTitleBar"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.Appx.IAppxTitleBar AppxTitleBar
    {
        get => CheckAccess(ref s_appxTitleBar);
    }

    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.Appx.IAppxTitleBarButton"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.Appx.IAppxTitleBarButton AppxTitleBarButton
    {
        get => CheckAccess(ref s_appxTitleBarButton);
    }

    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.Commands.ICommandBarService"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.Commands.ICommandBarService CommandBarService
    {
        get => CheckAccess(ref s_commandBarService);
    }

    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.ContextMenu.IContextMenuService"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.ContextMenu.IContextMenuService ContextMenuService
    {
        get => CheckAccess(ref s_contextMenuService);
    }

    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.Game.IGameService"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.Game.IGameService GameService
    {
        get => CheckAccess(ref s_gameService);
    }

    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.Logging.ILoggingService"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.Logging.ILoggingService LoggingService
    {
        get => CheckAccess(ref s_loggingService);
    }

    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.MRT.IMRTCoreService"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.MRT.IMRTCoreService MRTCoreService
    {
        get => CheckAccess(ref s_mRTCoreService);
    }

    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.Navigation.INavigationViewManagerFactory"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.Navigation.INavigationViewManagerFactory NavigationViewFactory
    {
        get => CheckAccess(ref s_navigationViewFactory);
    }

    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.Settings.ISettingsService"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.Settings.ISettingsService SettingsService
    {
        get => CheckAccess(ref s_settingsService);
    }

    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.Themes.IThemeService"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.Themes.IThemeService ThemeService
    {
        get => CheckAccess(ref s_themeService);
    }

    /// <summary>
    /// 获取全局静态共享的 <see cref="global::GZSkinsX.SDK.WindowManager.IWindowManagerService"/> 对象实例
    /// </summary>
    public static global::GZSkinsX.SDK.WindowManager.IWindowManagerService WindowManagerService
    {
        get => CheckAccess(ref s_windowManagerService);
    }

    /// <summary>
    /// 从已加载的所有组件中获取导出的类型实例
    /// </summary>
    /// <typeparam name="T">需要获取的类型</typeparam>
    /// <returns>返回 <typeparamref name="T"/> 的实例</returns>
    public static T Resolve<T>() where T : class
    {
        if (_compositionHost is null)
            throw new global::System.InvalidOperationException();

        return _compositionHost.GetExport<T>();
    }

    /// <summary>
    /// 尝试从已加载的所有组件中获取导出的类型实例
    /// </summary>
    /// <typeparam name="T">ExportAttribute 中所声明的导出类型</typeparam>
    /// <param name="value">已获取到的类型实例，但如果获取失败则会返回 default</param>
    /// <returns>当获取成功时返回 true，否则返回 false</returns>
    public static bool TryResolve<T>([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T? value) where T : class
    {
        if (_compositionHost is null)
            throw new global::System.InvalidOperationException();

        return _compositionHost.TryGetExport<T>(out value);
    }

    /// <summary>
    /// 用于获取已导出的类型的组件容器
    /// </summary>
    private static global::System.Composition.Hosting.CompositionHost? _compositionHost;

    /// <summary>
    /// 检查和获取指定导出类型的成员对象
    /// </summary>
    /// <typeparam name="T">需要获取对象导出类型</typeparam>
    /// <param name="service">需要检查的成员对象</param>
    /// <returns>已获取的非空的 <typeparamref name="T"/> 类型对象实例</returns>
    /// <exception cref="global::System.InvalidOperationException">当应用程序未初始化，或找不到指定 <typeparamref name="T"/> 导出类型的对象时发生</exception>
    private static T CheckAccess<T>([global::System.Diagnostics.CodeAnalysis.NotNull] ref T? service) where T : class
    {
        if (service is null)
        {
            if (_compositionHost is null)
            {
                throw new global::System.InvalidOperationException("The main app is not initialized!");
            }

            service = _compositionHost.GetExport<T>();
        }

        return service;
    }
    
    private static global::GZSkinsX.SDK.AccessCache.IFutureAccessService? s_futureAccessService;
    private static global::GZSkinsX.SDK.AccessCache.IMostRecentlyUsedService? s_mostRecentlyUsedItemService;
    private static global::GZSkinsX.SDK.Appx.IAppxWindow? s_appxWindow;
    private static global::GZSkinsX.SDK.Appx.IAppxTitleBar? s_appxTitleBar;
    private static global::GZSkinsX.SDK.Appx.IAppxTitleBarButton? s_appxTitleBarButton;
    private static global::GZSkinsX.SDK.Commands.ICommandBarService? s_commandBarService;
    private static global::GZSkinsX.SDK.ContextMenu.IContextMenuService? s_contextMenuService;
    private static global::GZSkinsX.SDK.Game.IGameService? s_gameService;
    private static global::GZSkinsX.SDK.Logging.ILoggingService? s_loggingService;
    private static global::GZSkinsX.SDK.MRT.IMRTCoreService? s_mRTCoreService;
    private static global::GZSkinsX.SDK.Navigation.INavigationViewManagerFactory? s_navigationViewFactory;
    private static global::GZSkinsX.SDK.Settings.ISettingsService? s_settingsService;
    private static global::GZSkinsX.SDK.Themes.IThemeService? s_themeService;
    private static global::GZSkinsX.SDK.WindowManager.IWindowManagerService? s_windowManagerService;
}
